### ISSUE TITLE
It actually worked... for some time

### ISSUE THREAD

**Issue by Ace2213** [Themroc/humhub_mobile-sidebar#1]
I wanted this to work so bad. I don't even know how I did it. I gave up and then after some time it started appearing by itself, and it was glorious. So I force enabled it across the site for everyone. But now I went to check again and it's gone.

And even while it was working, it wasn't showing up in the dashboard. Not sure if that's intentional. But since most widgets appear in the dashboard and are never seen by mobile users, I think it'd be great to enable it for the dashboard as well. Basically a system wide global toggle. 

IMO this shouldn't be an optional module. It should be a core module because it's part of the UI. Without it, mobile users simply don't have a sidebar.

Keep up the great work and let me know if I can help in any way!

**Comment by Themroc** [comment]
Yeah, i thought of that, but the dashboard is not like spaces or profiles, there's no menu to add a button. But now that you mention it, seems to me a better place for the switch would be topbar2, near "search". Plenty of room there.
Meanwhile, does it come back when you click your browsers "reload"-button?

**Comment by Ace2213** [comment]
I tried refreshing several pages and accessing them through ajax last night before posting this. It didn't work. But now it's somehow back again

I agree. The location of the button is a bit confusing. Plus, having it near the search button would make it look more official and less hacky.

**Comment by Themroc** [comment]
You might wanna try https://github.com/Themroc/humhub_mobile-sidebar/releases/download/v0.2/humhub_mobile-sidebar_v0.2.tar.xz

**Comment by Ace2213** [comment]
That didn't work at all for me. I tried refreshing and going to multiple pages (profiles, spaces and dashboard) and nothing ever showed up in the topbar or in the previous position.

Could it be because of the way I installed it? I removed the directory of the old version and extracted the new one under the same name. It was already enabled in my admin view but the "set as default" option was gone (which is great)

**Comment by Ace2213** [comment]
It's working now!

No idea why. I went and did something else then I tried again and now it's there. I love it. Great work. Hopefully it gets added as a core module

**Comment by Themroc** [comment]
When you just replace module code, delete protected/runtime/cache/* to make it work. Or wipe it out, unzip and re-activate via admin-interface.

Yeah, that "set as default" was rubbish, shouldn't have been there. My mistake.

If it's suitable for core i dunno... I for one wouldn't want it in my core as it is now. It's an ugly hack and makes many assumptions about how the theme is organized. It works only with the original theme or variations thereof where only some colors/fonts are changed. But a fundamentally new theme will most likely break it.

Anyway, glad it works for you! Thanks for testing, i'll also give it a go now :)

**Comment by Ace2213** [comment]
I think most people are running a theme based on the default one, or one that wouldn't conflict with your module. 

I don't know how it works, but it works. And if it gets added to core then they could make sure that nothing interferes with its location. 

Honestly, they should have come up with this themselves. Because until now, the sidebar did not exist for mobile users. That includes the tour, ads, all kinds of modules and widgets.

**Comment by Ace2213** [comment]
I ended up customizing my theme to display the sidebar widgets within the page itself for mobile users. For anyone interested, this is done by default in the [FlatHub theme](https://github.com/sashatravkina/humhub-themes-flathub-v2). You can take those elements and add them to your theme and make any modifications you want.

By default, the FlatHub implementation shows the sidebar widgets above the stream in the user's profile and below the stream in the dashboard and in spaces.
